apiVersion: v1
kind: Service
metadata:
  name: aks-storage-app-scala-service
  labels:
    app: aks-storage-app-scala
spec:
  type: LoadBalancer
  selector:
    app: aks-storage-app-scala
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
